task:
  use_compute_credits: true
  compute_engine_instance:  # https://cirrus-ci.org/guide/custom-vms/#custom-compute-engine-vms
    image_project: ubuntu-os-cloud
    image: family/ubuntu-2404-lts-amd64  # https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts
    nested_virtualization: true
    cpu: 4  # 1 is enough, but nested_virtualization machines have at least 4
    memory: 2G
  timeout_in: 20m
  snapcraft_pull_script:
    - snap install snapcraft --classic
    - snap install multipass
    - snapcraft pull
  ci_script:
    - snapcraft
