task:
  use_compute_credits: true
  compute_engine_instance:  # https://cirrus-ci.org/guide/custom-vms/#custom-compute-engine-vms
    image_project: ubuntu-os-cloud
    image: family/ubuntu-2404-lts-amd64  # https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts
    cpu: 1
    memory: 2G
  timeout_in: 20m
  install_packages_script:
    - apt-get update
    - apt-get install snapd
  snapcraft_pull_script:
    - snap install snapcraft multipass
    - snapcraft pull
  ci_script:
    - snapcraft
