task: #bla
  use_compute_credits: true
  compute_engine_instance:  # https://cirrus-ci.org/guide/custom-vms/#custom-compute-engine-vms
    image_project: ubuntu-os-cloud
    image: family/ubuntu-2004-lts  # https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts
    cpu: 1
    memory: 2G
  timeout_in: 20m
  env:
    DOCKER_PACKAGES: "snapcraft"
  install_packages_script:
    - apt-get update
    - apt-get install --no-install-recommends --no-upgrade -qq $DOCKER_PACKAGES
  snapcraft_pull_script:
    - snapcraft pull
  ci_script:
    - snapcraft
