name: bitcoin-core
version: '29.0'
summary: Fully validating Bitcoin peer-to-peer network node, wallet and GUI
description: |
  Bitcoin Core connects to the Bitcoin peer-to-peer network to download and
  fully validate blocks and transactions. It also includes a wallet and
  graphical user interface.

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]
  - build-on: [amd64, arm64, armhf]
    build-for: [armhf]
  - build-on: [amd64, arm64, ppc64el]
    build-for: [ppc64el]
  - build-on: [amd64, arm64, riscv64]
    build-for: [riscv64]

apps:
  daemon:
    command: bin/bitcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/bitcoin-core/common/.bitcoin/ instead of
      # ~/snap/bitcoin-core/current/.bitcoin/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: bin/bitcoin-qt
    extensions: [kde-neon]
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      # https://forum.snapcraft.io/t/kde-neon-6-extension-snap-qt-qpa-platform-overwritten/46054
      WAYLAND_DISPLAY: unset
      QT_QPA_PLATFORM: xcb
  cli:
    command: bin/bitcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: bin/bitcoin-tx
    environment:
      HOME: $SNAP_USER_COMMON
  wallet:
    command: bin/bitcoin-wallet
    plugs: [home, removable-media]
    environment:
      HOME: $SNAP_USER_COMMON
  util:
    command: bin/bitcoin-util
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  bitcoin-core:
    plugin: nil
    override-build: |
      env | grep "CRAFT\|SNAP" | sort
      bitcoin_core_version=$(craftctl get version)
      curl -LO https://bitcoincore.org/bin/bitcoin-core-${bitcoin_core_version}/SHA256SUMS
      curl -LO https://bitcoincore.org/bin/bitcoin-core-${bitcoin_core_version}/bitcoin-${bitcoin_core_version}.tar.gz
      curl -LO https://bitcoincore.org/bin/bitcoin-core-${bitcoin_core_version}/bitcoin-${bitcoin_core_version}-${CRAFT_ARCH_TRIPLET_BUILD_FOR}.tar.gz
      echo "94ec151f452a221393d08f6b02fb30baacbeb59f194611f49069e7f5509b46fe  SHA256SUMS" | sha256sum --check
      sha256sum --ignore-missing --check SHA256SUMS
      tar -xvf bitcoin-${bitcoin_core_version}-${CRAFT_ARCH_TRIPLET_BUILD_FOR}.tar.gz
      tar -xvf bitcoin-${bitcoin_core_version}.tar.gz
      if [ "$CRAFT_ARCH_TRIPLET_BUILD_ON" != "$CRAFT_ARCH_TRIPLET_BUILD_FOR" ]; then
        echo "Skipping tests when cross-compiling."
      else
        echo "Running tests ..."
        bitcoin-${bitcoin_core_version}/bin/test_bitcoin
      fi
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoind
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoin-qt
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoin-cli
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoin-tx
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoin-wallet
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bitcoin-${bitcoin_core_version}/bin/bitcoin-util
      curl -LO https://raw.githubusercontent.com/bitcoin/bitcoin/v${bitcoin_core_version}/share/pixmaps/bitcoin128.png
      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps bitcoin128.png
    build-packages:
      - curl
    stage-packages:
      - libxcb1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libfontconfig1
      - libfreetype6
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-shm0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xkb1
