name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - name: Uninstall Docker, per https://documentation.ubuntu.com/lxd/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker
        run: |
          sudo systemctl stop docker.service docker.socket containerd.service
          sudo apt-get purge -y docker-ce docker-ce-cli containerd.io
          # Clean up any leftover iptables rules Docker might have left
          sudo iptables -P FORWARD ACCEPT
          sudo iptables -F
      - name: Install Snapcraft and LXD
        run: |
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo /snap/bin/lxd init --auto
      - name: Pull Snap dependencies
        run: sudo snapcraft pull --use-lxd
      - name: Build Snap
        run: sudo snapcraft pack --use-lxd
